### ISSUE TITLE
2019 Primary Precinct Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ms#100]
Data entry/OCR from PDF files. For each county, grab the [Republican](https://www.sos.ms.gov/Elections-Voting/Pages/2019-Republican-Primary.aspx) and [Democratic](https://www.sos.ms.gov/Elections-Voting/Pages/2019-Democratic-Primary.aspx) files and combine their contents into one CSV. 

The resulting CSV file should have one row per candidate result for each county. [Here's](https://github.com/openelections/openelections-data-ms/blob/master/2015/counties/20150804__ms__primary__adams__precinct.csv) an example of a finished file. Please match the headers of that file. The precinct name is displayed in vertical headers in the PDF and should be entered exactly as it appears. For vote totals with an "X", enter "X".

Enter the following races ONLY: Governor, Lieutenant Governor, Secretary of State, Attorney General, State Auditor, State Treasurer, Commissioner of Agriculture & Commerce, Commissioner of Insurance, State Senate, State House

Enter candidate and precinct names exactly as they appear. The candidate party is to the right of the candidate name. State Senate and House races get a district value (just the number).

The filenames will be: `20190806__ms__primary__{county}__precinct.csv`

- [x] Adams
- [x] Alcorn
- [x] Amite
- [x] Attala
- [x] Benton
- [x] Bolivar
- [x] Calhoun
- [x] Carroll
- [x] Chickasaw
- [x] Choctaw
- [x] Claiborne
- [x] Clarke
- [x] Clay
- [x] Coahoma
- [x] Copiah
- [x] Covington
- [x] Desoto
- [x] Forrest
- [x] Franklin
- [x] George
- [x] Greene
- [x] Grenada
- [x] Hancock
- [x] Harrison
- [x] Hinds
- [x] Holmes
- [x] Humphreys
- [x] Issaquena
- [x] Itawamba
- [x] Jackson
- [x] Jasper
- [x] Jefferson Davis
- [x] Jefferson
- [x] Jones
- [x] Kemper
- [x] Lafayette
- [x] Lamar
- [x] Lauderdale
- [x] Lawrence
- [x] Leake
- [x] Lee
- [x] Leflore
- [x] Lincoln
- [x] Lowndes
- [x] Madison
- [x] Marion
- [x] Marshall
- [x] Monroe
- [x] Montgomery
- [x] Neshoba
- [x] Newton
- [x] Noxubee
- [x] Oktibbeha
- [x] Panola
- [x] Pearl River
- [x] Perry
- [x] Pike
- [x] Pontotoc
- [x] Prentiss
- [x] Quitman
- [x] Rankin
- [x] Scott
- [x] Sharkey
- [x] Simpson
- [x] Smith
- [x] Stone
- [x] Sunflower
- [x] Tallahatchie
- [x] Tate
- [x] Tippah
- [x] Tishomingo
- [x] Tunica
- [x] Union
- [x] Walthall
- [x] Warren
- [x] Washington
- [x] Wayne
- [x] Webster
- [x] Wilkinson
- [x] Winston
- [x] Yalobusha
- [x] Yazoo

**Comment by selichko** [comment]
I'm working on Franklin County.
