### ISSUE TITLE
2020 Primary Election Precinct Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ms#113]
Data entry/OCR from files [here](https://www.sos.ms.gov/Elections-Voting/Pages/2020-Democratic-Primary.aspx) and [here](https://www.sos.ms.gov/Elections-Voting/Pages/2020-Republican-Primary.aspx). Combine the Democratic and Republican results into a single CSV file, using the instructions in the [README](https://github.com/openelections/openelections-data-ms/blob/master/README.md). An example CSV is [here](https://github.com/openelections/openelections-data-ms/blob/master/2016/counties/20160308__ms__primary__adams__precinct.csv). The filename for the 2020 primaries would be: `20200310__ms__primary__{county}__precinct.csv`, with the county name in lower case and spaces replaced with underscores.

- [x] Adams
- [x] Alcorn
- [x] Amite
- [x] Attala
- [x] Benton
- [x] Bolivar
- [x] Calhoun
- [x] Carroll
- [x] Chickasaw
- [x] Choctaw
- [x] Claiborne
- [x] Clarke
- [x] Clay
- [x] Coahoma
- [x] Copiah
- [x] Covington
- [x] Desoto
- [x] Forrest
- [x] Franklin
- [x] George
- [x] Greene
- [x] Grenada
- [x] Hancock
- [x] Harrison
- [x] Hinds
- [x] Holmes
- [x] Humphreys
- [x] Issaquena (Republican only)
- [x] Itawamba
- [x] Jackson
- [x] Jasper
- [x] Jefferson Davis
- [x] Jefferson
- [x] Jones
- [x] Kemper
- [x] Lafayette
- [x] Lamar
- [x] Lauderdale
- [x] Lawrence
- [x] Leake
- [x] Lee
- [x] Leflore
- [x] Lincoln
- [x] Lowndes
- [x] Madison
- [x] Marion
- [x] Marshall
- [x] Monroe
- [x] Montgomery
- [x] Neshoba
- [x] Newton
- [x] Noxubee
- [x] Oktibbeha
- [x] Panola
- [x] Pearl River
- [x] Perry
- [x] Pike
- [x] Pontotoc
- [x] Prentiss
- [x] Quitman
- [x] Rankin
- [x] Scott
- [x] Sharkey
- [x] Simpson
- [x] Smith
- [x] Stone
- [x] Sunflower
- [x] Tallahatchie
- [x] Tate
- [x] Tippah
- [x] Tishomingo
- [x] Tunica
- [x] Union
- [x] Walthall
- [x] Warren
- [x] Washington
- [x] Wayne
- [x] Webster
- [x] Wilkinson
- [x] Winston
- [x] Yalobusha
- [x] Yazoo

**Comment by smcalilly** [comment]
I'm going to work on Adams county.

**Comment by smcalilly** [comment]
I'm going to try and knock out some of the bigger or more diverse counties. For now, I'm committing to do **Lee** and **Lafayette** counties for both the Republican and Democratic primaries. 

If anybody is not from Mississippi and doesn't know where to start, these are also notable (or at least might have some interesting data to look at):
- Desoto (near Memphis)
- Oktibbeha (college town)
- Madison (capital metro area)
- Rankin (capital metro area)
- Washington (arguably heart of the Delta)
- Sunflower (arguably heart of the Delta)
- Leflore (arguably heart of the Delta)
- Holmes (one of the poorest counties in the US: https://www.theguardian.com/us-news/2015/nov/15/poorest-town-in-poorest-state-segregation-is-gone-but-so-are-the-jobs)
- Warren (Vicksburg)
- Adams (Natchez)
- Forrest (Hattiesburg metro)
- Jones (sort of Hattiesburg metro)
- Lauderdale (Meridian)
- Hancock (MS gulf coast)
- Harrison (MS gulf coast)
- Jackson (MS gulf coast)

**Comment by dwillis** [comment]
@smcalilly Sounds awesome, thank you!
