### ISSUE TITLE
2020 general results for Washington County missing half of precincts

### ISSUE THREAD

**Issue by mileswwatkins** [openelections/openelections-data-ms#120]
Looks like the OCR missed the first of two pages of precincts in the PDF, and only got the latter. (The 2020 primary scrape of Washington County seems to have fetched all precincts.)

[The CSV for Washington County](https://github.com/openelections/openelections-data-ms/blob/master/2020/counties/20201103__ms__general__washington__precinct.csv) contains (alphabetically) the precincts `Leland Rotary Club` through `Washington County Convention Center`, but is missing `Arcola Technology Center` through `Leland Health Department`.

<img width="925" alt="Screen Shot 2021-01-17 at 17 04 16" src="https://user-images.githubusercontent.com/4959135/104861799-1a2fe180-58e6-11eb-856b-ae5ed8bcf298.png">

<img width="911" alt="Screen Shot 2021-01-17 at 17 04 22" src="https://user-images.githubusercontent.com/4959135/104861802-1c923b80-58e6-11eb-8e51-675de408e678.png">

**Comment by mileswwatkins** [comment]
Thanks @dwillis! Can you propagate this change/fix to the statewide precinct file? (https://github.com/openelections/openelections-data-ms/blob/master/2020/20201103__ms__general__precinct.csv)

**Comment by dwillis** [comment]
@mileswwatkins done!
