### ISSUE TITLE
Various Fixes in 2023 General File

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-data-ms#186]
Thanks for putting this file together, I compared the outputs of the two files and was able to find some fixes.

_20231107__ms__general__precinct.csv_

- **Carroll**: forgot Salem, West Carroll, West Vaiden precincts for some races on PDF page that includes House of Rep 46
- **Yazoo**: David McRae is missing 139 votes in East Bentonia precinct
- **Alcorn**: Union Center precinct missing for State House of Reps District 4
- **Hancock**: Precinct mislabeling affecting "Standard", "Waveland East", "Waveland West" and "West Shoreline Park" for first chunk of results in PDF
- **Adams**: For Albert Butler, two precincts are mislabeled ("Dist. 4, Carpenter Precinct" should be "Dist. 4, Pine Ridge Precinct" and "Dist. 4, Morgantown Precinct" should be "Dist. 5, Airport Precinct") and two precincts then need votes (the above two that are changed).
- **Pike**: Daryl L. Porter Jr. should be State House 98 candidate

**Cleaning candidates** (the below is a dictionary from the incorrect name to the correct one, sometimes it is the name and other times it is the district, note for the "Malinski" ones there appear to be multiple spellings but I just went with one. Two of these also just standardize the quotes / apostrophes used.)
"Nicole Atkins Boyd-:-REP-:-State Senate-9":"Nicole Akins Boyd-:-REP-:-State Senate-9",
"Bill Piggott-:-REP-:-State House-99":"Bill Pigott-:-REP-:-State House-99",
"Chiekh A. Taylor-:-DEM-:-State House-38":"Cheikh A. Taylor-:-DEM-:-State House-38",
'''Joseph F. "Jody" Steverson-:-REP-:-State House-4''':'''Joseph F. 'Jody' Steverson-:-REP-:-State House-4''',
'''Lester E. "Bubba" Carpenter-:-REP-:-State House-1''':'''Lester E. 'Bubba' Carpenter-:-REP-:-State House-1''',
"Karl Malinsky Gibbs-:-DEM-:-State House-36":"Karl Malinski Gibbs-:-DEM-:-State House-36",
"Lydla Chassaniol-:-REP-:-State Senate-14":"Lydia Chassaniol-:-REP-:-State Senate-14",
'Angela Ford Turner-:-DEM-:-State Senate-16': 'Angela Turner Ford-:-DEM-:-State Senate-16',
'Angela Turner Ford-:-DEM-:-State Senate-15': 'Angela Turner Ford-:-DEM-:-State Senate-16'

**20231107__ms__general__county.csv**

- **Harrison**: Philman A. Ladner votes should be 4396
- **Lamar**: Votes here for "Neil S. Whaley" should be for Lafayette County
- **Pearl River**: Votes here for State Senate District 24 should be in Panola County
- **Jones**: Name "Charles 'Chuck' Blackwell Republican" should just be "Charles 'Chuck' Blackwell"
- **(Multiple)**: Chuck Younger should be in district 17, not 24

**Comment by peter-redistricting-data-hub** [comment]
If you'd like, I can generate the files with these changes and post to this thread, but understand if you're more comfortable checking yourself.

**Comment by dwillis** [comment]
@peter-redistricting-data-hub thank you! a patch with these changes would be excellent if you have time to do it.
