### ISSUE TITLE
First row has a thousands separator, and the rest don't

### ISSUE THREAD

**Issue by danfowler** [openelections/openelections-data-ms#38]
This can cause pain when trying to parse:

https://github.com/openelections/openelections-data-ms/blob/master/2016/20161108__ms__general.csv

<img width="998" alt="screen shot 2017-04-18 at 15 55 43" src="https://cloud.githubusercontent.com/assets/772616/25123242/f03ccf0e-2451-11e7-9f4b-210543898a19.png">

We are developing some automated tabular data validation tools (https://github.com/frictionlessdata/goodtables.io) that can check for these kinds of issues.

**Comment by dwillis** [comment]
Good catch, @danfowler, thanks!
