### ISSUE TITLE
2016 general precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ms#40]
Data entry/OCR from files [here](http://sos.ms.gov/elections/electionresults_aspx/elections_results_2016_county.aspx): 

The generated CSVs are named: `20161108__ms__general__{county}__precinct.csv`, where `{county}` is the lowercased name of the county.

Headers for the files are: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

We need federal and state offices, including State Senate and State House.

- [x] Adams
- [x] Alcorn
- [x] Amite
- [x] Attala
- [x] Benton
- [x] Bolivar
- [x] Calhoun
- [x] Carroll
- [x] Chickasaw
- [x] Choctaw
- [x] Claiborne
- [x] Clarke
- [x] Clay
- [x] Coahoma
- [x] Copiah
- [x] Covington
- [x] Desoto
- [x] Forrest
- [x] Franklin
- [x] George
- [x] Greene
- [x] Grenada
- [x] Hancock
- [x] Harrison
- [x] Hinds
- [x] Holmes
- [x] Humphreys
- [x] Issaquena
- [x] Itawamba
- [x] Jackson
- [x] Jasper
- [x] Jefferson Davis
- [x] Jefferson
- [x] Jones
- [x] Kemper
- [x] Lafayette
- [x] Lamar
- [x] Lauderdale
- [x] Lawrence
- [x] Leake
- [x] Lee
- [x] Leflore
- [x] Lincoln
- [x] Lowndes
- [x] Madison
- [x] Marion
- [x] Marshall
- [x] Monroe
- [x] Montgomery
- [x] Neshoba
- [x] Newton
- [x] Noxubee
- [x] Oktibbeha
- [x] Panola
- [x] Pearl River
- [x] Perry
- [x] Pike
- [x] Pontotoc
- [x] Prentiss
- [x] Quitman
- [x] Rankin
- [x] Scott
- [x] Sharkey
- [x] Simpson
- [x] Smith
- [x] Stone
- [x] Sunflower
- [x] Tallahatchie
- [x] Tate
- [x] Tippah
- [x] Tishomingo
- [x] Tunica
- [x] Union
- [x] Walthall
- [x] Warren
- [x] Washington
- [x] Wayne
- [x] Webster
- [x] Wilkinson
- [x] Winston
- [x] Yalobusha
- [x] Yazoo

**Comment by todrobbins** [comment]
Anyone having success using [Tabula](http://tabula.technology/)?

**Comment by dwillis** [comment]
@todrobbins It depends on the file, but in most cases no. OCR is an option in many cases, though.

**Comment by todrobbins** [comment]
Alright, I ran `Adams.pdf` through Acrobat OCR and then through Tabula, and the results aren't completely useless:

![screen shot 2017-05-09 at 12 26 37 pm](https://cloud.githubusercontent.com/assets/158590/25866191/dec4300c-34b2-11e7-99f2-04373bb2736d.png)

But I see what you mean.

**Comment by dwillis** [comment]
For some of the larger counties, it might be easier to see if they posted the original electronic PDF on their website and try that.

**Comment by stedy** [comment]
I'm gonna start from Yazoo and work my way backwards

**Comment by dwillis** [comment]
Hey @stedy - we've got some contributions for the other MS counties, so let me know if you have any you're working on currently if you can.

**Comment by stedy** [comment]
oh nice, thanks! I have Oktibbeha done but not yet committed
