### ISSUE TITLE
Convert 2016 State Legislative Special Elections

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ms#67]
From [here](http://www.sos.ms.gov/Elections-Voting/Pages/2016-Special-Election.aspx):

Headers for the files are: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For special generals, the generated CSVs are named: `2016{MMDD}__ms__special__general__{county}__precinct.csv`, where `{county}` is the lowercased name of the county.

For special general runoffs, the generated CSVs are named: `2016{MMDD}__ms__special__general_runoff__{county}__precinct.csv`, where `{county}` is the lowercased name of the county.

- [x] State Senate, District 25 General
- [x] House District 29 General
- [x] House District 29 General Runoff
- [x] State House of Representatives District 72 General
- [x] State House of Representatives District 72 General Runoff
- [x] State House of Representatives District 89 General
- [x] State House of Representatives District 89 General Runoff
- [x] State House of Representatives District 106 General
- [x] State House of Representatives District 106 General Runoff

**Comment by srge1827** [comment]
They should be by County, not race, correct? So there would be senate-25 and house 72 in the same file?

**Comment by srge1827** [comment]
Different files by county or election? Because the 3 files are by election and all have multiple counties in there but the instructions make it seem like they should be separated by county and not election.

**Comment by dwillis** [comment]
Hey @srge1827 - the CSV files should be by election and can contain multiple counties/races.
