### ISSUE TITLE
Parse County-Level Results for 2015 General Election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ms#72]
Using Tabula and this [PDF](http://sos.ms.gov/elections/electionresults/2015General/certified%20results/2015%20General%20Election%20Official%20Statewide%20Recapitulation.pdf), generate a CSV file that looks like [this one from 2011](https://github.com/openelections/openelections-data-ms/blob/master/2011/20111108__ms__general.csv) for the following offices:

* Governor
* Lieutenant Governor
* Secretary of State
* Attorney General
* State Auditor
* State Treasurer
* Commissioner of Agriculture & Commerce
* Commissioner of Insurance
* State Senate
* State House

**Comment by acolter** [comment]
I'm on it.
